services:
  reservetions:
    build:
      context: .
      dockerfile: ./apps/reservetions/Dockerfile
      target: development
    command: pnpm run start:dev reservetions 
    env_file:
      - ./apps/reservetions/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/apps
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo